/**
  ******************************************************************************
  * @file    usb_device.h
  * @brief   This file contains the prototypes for USB device initialization.
  ******************************************************************************
  * @attention
  *
  * This file was generated by STM32CubeMX and contains initialization functions
  * for the USB peripheral.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __USB_DEVICE_H
#define __USB_DEVICE_H

#ifdef __cplusplus
 extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "usbd_core.h"        // USB core functions
#include "usbd_dfu.h"         // DFU class (Device Firmware Upgrade)
#include "usbd_desc.h"        // USB device descriptors
#include "usbd_ctlreq.h"      // USB control requests

/* USB Device Core handle */
extern USBD_HandleTypeDef hUsbDeviceFS;

/* Function prototypes */
void MX_USB_DEVICE_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __USB_DEVICE_H */
