#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
 extern "C" {
#endif

#include "stm32f7xx_hal.h"  // Include HAL for STM32F7

// ADC Handle declaration
extern ADC_HandleTypeDef hadc1;

// USB device handle declaration (generated by STM32CubeMX)
extern USB_HandleTypeDef hUsbDeviceFS;

// ADC values array
extern uint16_t adc_values[8];

// Function prototypes
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_ADC_Init(void);
void MX_USB_DEVICE_Init(void);
void JumpToDFU(void);
void ExitDFUAndReboot(void);

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
